notifications:
    email:
        recipients:
            - alinenachescu033@gmail.com

notifications:
    irc: "chat.freenode.net#cruce-devel"

language: c
compiler: gcc
sudo: required

before_install:
    - sudo apt-get install xorriso

install:
    - wget -O build.tar.gz "https://onedrive.live.com/download?cid=9B17C13D0B35F82E&resid=9B17C13D0B35F82E%21401&authkey=AMivmxXl5pr8kzc"
    - tar -zxvf build.tar.gz

script:
    - ./linux_compile.sh clean-all
    - ./linux_compile.sh build-all
