notifications:
    irc: "chat.freenode.net#cruce-devel"

language: c
compiler: gcc

addons:
    apt:
        packages:
        - libc6-dev-i386
        - gcc-multilib
        - g++-multilib

before_install:
    - pip install --user cpp-coveralls

install:
    - ./linux_x86_64_getDependencies.sh

script:
    - ./linux_x86_64_compile.sh clean x86_32
    - ./linux_x86_64_compile.sh build x86_32 notGenerateIso
    - ./linux_runTests.sh run x86_32
    - ./linux_runTests.sh run x86_64

after_success:
    - coveralls -r /home/travis/build/EnachescuAlin/PhiOS -b /home/travis/build/EnachescuAlin/PhiOS/tests/bin -i /home/travis/build/EnachescuAlin/PhiOS/kernel/src/memory/bitmap_pma.c -i kernel/src/memory/paa.c -i ksnprintf_helper.c -i ksnprintf.c -i kstdlib.c -i kstring.c -i kvsnprintf.c --gcov gcov --gcov-options '\-lp'
